"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Users", [
      {
        email: "example1@example1.com",
        password: "123",
        name: "ChanChan",
        phone: "1111111111",
        otp: "HSDQDC",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example2example2.com",
        password: "123",
        name: "KongKong",
        phone: "2222222222",
        otp: "HSDQDC",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example3@example3.com",
        password: "123",
        name: "JanJan",
        phone: "3333333333",
        otp: "HSDQDC",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example4@example4.com",
        password: "123",
        name: "HemHem",
        phone: "4444444444",
        otp: "HSDQDC",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example5@example5.com",
        password: "123",
        name: "LiuLiu",
        phone: "5555555555",
        otp: "HSDQDC",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example6@example6.com",
        password: "123",
        name: "PingPing",
        phone: "6666666666",
        otp: "JKSDLA",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example7@example7.com",
        password: "123",
        name: "TangTang",
        phone: "7778889999",
        otp: "WQERTY",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example8@example8.com",
        password: "123",
        name: "FangFang",
        phone: "8887771234",
        otp: "ZXCVBN",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example9@example9.com",
        password: "123",
        name: "LanLan",
        phone: "9994441234",
        otp: "QWERAS",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example10@example10.com",
        password: "123",
        name: "LingLing",
        phone: "5551236789",
        otp: "TYUIOP",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example11@example11.com",
        password: "123",
        name: "KimKim",
        phone: "1122334455",
        otp: "GHJKOP",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example12@example12.com",
        password: "123",
        name: "MinMin",
        phone: "9988776655",
        otp: "POIUYT",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example13@example13.com",
        password: "123",
        name: "HanHan",
        phone: "6677889900",
        otp: "LKJHGF",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example14@example14.com",
        password: "123",
        name: "XinXin",
        phone: "1234567890",
        otp: "DFGRTY",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example15@example15.com",
        password: "123",
        name: "ZoeZoe",
        phone: "2233445566",
        otp: "MNBVCX",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example16@example16.com",
        password: "123",
        name: "LeoLeo",
        phone: "4455667788",
        otp: "QAZWSX",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example17@example17.com",
        password: "123",
        name: "RoyRoy",
        phone: "5566778899",
        otp: "EDCRFV",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example18@example18.com",
        password: "123",
        name: "YanYan",
        phone: "6677889901",
        otp: "TGHBVC",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example19@example19.com",
        password: "123",
        name: "SueSue",
        phone: "7788990011",
        otp: "YUIOKL",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example20@example20.com",
        password: "123",
        name: "JayJay",
        phone: "8899001122",
        otp: "ZXCVBN",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example21@example21.com",
        password: "123",
        name: "AmyAmy",
        phone: "9988223344",
        otp: "QWERTY",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example22@example22.com",
        password: "123",
        name: "TomTom",
        phone: "8877665544",
        otp: "ASDFGH",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example23@example23.com",
        password: "123",
        name: "NinaNina",
        phone: "7766554433",
        otp: "ZXCVBN",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example24@example24.com",
        password: "123",
        name: "EliEli",
        phone: "6655443322",
        otp: "POIUYT",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example25@example25.com",
        password: "123",
        name: "SamSam",
        phone: "5544332211",
        otp: "LKJHGF",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example26@example26.com",
        password: "123",
        name: "JenJen",
        phone: "4433221100",
        otp: "MNBVCX",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example27@example27.com",
        password: "123",
        name: "MaxMax",
        phone: "3322110099",
        otp: "QAZWSX",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example28@example28.com",
        password: "123",
        name: "EvaEva",
        phone: "2211009988",
        otp: "EDCRFV",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example29@example29.com",
        password: "123",
        name: "KaiKai",
        phone: "1100998877",
        otp: "TGHBVC",
        role: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        email: "example30@example30.com",
        password: "123",
        name: "RayRay",
        phone: "0099887766",
        otp: "YUIOPL",
        role: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
